//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 校园旧货交易登记系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_order
    {
        public int order_id { get; set; }
        public int goods_id { get; set; }
        public System.DateTime order_time { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
    
        public virtual base_goods base_goods { get; set; }
    }
}
