//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 校园旧货交易登记系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public base_goods()
        {
            this.base_order = new HashSet<base_order>();
        }
    
        public int goods_id { get; set; }
        public string goods_name { get; set; }
        public int user_id { get; set; }
        public int goods_status { get; set; }
        public double goods_price { get; set; }
        public System.DateTime goods_time { get; set; }
        public int is_change { get; set; }
        public string change_goods_name { get; set; }
        public int is_delete { get; set; }
    
        public virtual sys_user sys_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<base_order> base_order { get; set; }
    }
}
