//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 校园旧货交易登记系统.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetEntities : DbContext
    {
        public NetEntities()
            : base("name=NetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<base_goods> base_goods { get; set; }
        public virtual DbSet<base_order> base_order { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
    }
}
