//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 校园旧货交易登记系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_user()
        {
            this.base_goods = new HashSet<base_goods>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_passwod { get; set; }
        public string user_tele { get; set; }
        public string user_address { get; set; }
        public int user_sex { get; set; }
        public Nullable<int> is_delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<base_goods> base_goods { get; set; }
    }
}
